import React from "react";
import styled from "styled-components";

function HomeWoodBikes() {
  return (
    <Wrapper>
      <h1>Wood Bikes</h1>
      <p>
        Each manufactured frame is a work of art, unique due to the variable
        visual level of each part of wood that is used, it is functional because
        the weight is similar to that of aluminum frames, it is also a perfect
        component due to its excellent rigidity and vibration absorption.
        generated by the movements of the road providing a better experience and
        comfort over long distances
      </p>
    </Wrapper>
  );
}

export default HomeWoodBikes;

const Wrapper = styled.div`
  width: 350px;

  margin: 100px auto; 

  h1,
  p {
    text-align: left !important;
  }
  p {
    font-weight: 100;
    font-size: 18px;
  }
`;
